export const SET_LISTITEMS = 'SET_LISTITEMS';
export const FETCH_LISTITEMS_FAILED = 'FETCH_LISTITEMS_FAILED';

export const ADD_LISTITEM_SUCCESS = 'ADD_LISTITEM_SUCCESS';
export const ADD_LISTITEM_FAIL = 'ADD_LISTITEM_FAIL';

export const REMOVE_LISTITEM_SUCCESS = 'REMOVE_LISTITEM_SUCCESS';
export const REMOVE_LISTITEM_FAIL = 'REMOVE_LISTITEM_FAIL';

export const COMPLETE_LISTITEM_SUCCESS = 'COMPLETE_LISTITEM_SUCCESS';
export const COMPLETE_LISTITEM_FAIL = 'COMPLETE_LISTITEM_FAIL';
